### ISSUE TITLE
Request for an open source license

### ISSUE THREAD

**Issue by dnmmrdr** [jrmedd/nct-buses#2]
Hiya,

I was just wondering if it would be possible to attribute an open source license to this project?

I was hoping to use it as a basis for a personal project, for reference it was to create a module for a [Magic Mirror](https://magicmirror.builders/).

At present due to the lack of license I don't want to use the project in case I am not permitted to do so

Would be great if you could open source this project but if not, no worries!

Thanks

**Comment by jrmedd** [comment]
Hello! Yes, I'll add an open source license, no problem.
